root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - '@vue/eslint-config-typescript/recommended'
  - plugin:vue/vue3-recommended
  - plugin:vue-scoped-css/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  parser: '@typescript-eslint/parser'
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
plugins:
  - '@typescript-eslint'
  - prettier
  - vue
rules:
  prettier/prettier: error
